name: "Docker Build & Push"
description: "Build and push Docker images with caching to AWS ECR using Docker Buildx"
inputs:
  REPO:
    description: "Docker repository name (defaults to repo name)"
    required: false
  PACKAGE_JSON:
    description: "Path to package.json"
    required: false
    default: "package.json"
  ECR_USERNAME:
    description: "AWS ECR username"
    required: true
  ECR_REGION:
    description: "AWS region"
    required: false
    default: "us-west-2"
  CACHE_BUCKET:
    description: "S3 bucket for Docker build cache"
    required: false
    default: "local-builds-cache"
  DOCKERFILE:
    description: "Dockerfile path"
    required: false
    default: "Dockerfile.prod"
  SCAN_IMAGE:
    description: "Whether to scan the image with Trivy (true/false)"
    required: true
  IMAGE_TYPE:
    description: "Type of image to build (dev/prod/pull/test)"
    required: true
  IMAGE_TAG:
    description: "Additional tag for the image (e.g. 'latest')"
    required: true
  PLATFORM:
    description: "Target platform for the image (e.g. 'linux/amd64,linux/arm64')"
    required: false
    default: "linux/amd64"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Get version and set output
      shell: bash
      id: get-version
      run: |
        VERSION=$(jq -r .version package.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ inputs.ECR_REGION }}
    - name: Verify AWS Identity
      shell: bash
      run: |
        echo "Current AWS Identity:"
        aws sts get-caller-identity
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        GITHUB_SHA: ${{ github.sha }}
      shell: bash
      run: |
        REPO="${{ inputs.REPO }}"
        REPO_NAME="${REPO##*/}"
        PACKAGE_JSON="${{ inputs.PACKAGE_JSON }}"
        ECR_REGION="${{ inputs.ECR_REGION }}"
        PLATFORM="${{ inputs.PLATFORM }}"
        CACHE_BUCKET="${{ inputs.CACHE_BUCKET }}"
        DOCKERFILE="${{ inputs.DOCKERFILE }}"
        IMAGE_TYPE="${{ inputs.IMAGE_TYPE }}"
        VERSION=$(jq -r .version "$PACKAGE_JSON")
        IMAGE_TAG="${{ inputs.IMAGE_TAG }}"

        # Temporarily set version to 0.0.0 for caching
        echo "Temporarily setting version to 0.0.0 for caching purposes..."
        jq '.version = "0.0.0"' "$PACKAGE_JSON" > "$PACKAGE_JSON.tmp"
        mv "$PACKAGE_JSON.tmp" "$PACKAGE_JSON"
        echo "Modified package.json for caching:"
        cat "$PACKAGE_JSON"
        echo "Building and pushing Docker image with Buildx..."
        docker buildx build --platform "$PLATFORM" \
          --pull=false \
          --cache-from type=s3,region="$ECR_REGION",bucket="$CACHE_BUCKET",name=onoctave-cache \
          --cache-to type=s3,region="$ECR_REGION",bucket="$CACHE_BUCKET",name=onoctave-cache,mode=max,ignore-error=true \
          -t "$ECR_REGISTRY/$REPO_NAME:$IMAGE_TYPE-${IMAGE_TAG}" \
          -t "$ECR_REGISTRY/$REPO_NAME:$VERSION" \
          -f "$DOCKERFILE" \
          --push .
        echo "Restoring original version in package.json..."
        git checkout "$PACKAGE_JSON"

    - name: list images
      shell: bash
      run: docker image ls

    - name: Scan Docker image with Trivy
      shell: bash
      run: |
        ls -la
        REPO="${{ inputs.REPO }}"
        REPO_NAME="${REPO##*/}"
        echo "Repo name: $REPO_NAME"
        VERSION="${{ steps.get-version.outputs.version }}"
        #aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ inputs.ECR_USERNAME }}
        IMAGE="${{ inputs.ECR_USERNAME }}/$REPO_NAME:$VERSION"
        echo "Scanning $IMAGE for vulnerabilities..."
        #run base on input SCAN_IMAGE
        if [ "${{ inputs.SCAN_IMAGE }}" = "true" ]; then
          echo "Scanning enabled, running Trivy..."
          trivy image --severity CRITICAL,HIGH --exit-code 1 --skip-files "/usr/local/lib/node_modules/**" --ignore-unfixed $IMAGE
        else
          echo "Scanning disabled, skipping Trivy..."
        fi
        #trivy image --severity CRITICAL,HIGH,MEDIUM --exit-code 1 --ignore-unfixed $IMAGE
        #--exit-code 1 --ignore-unfixed $IMAGE